### ISSUE TITLE
TWRP for PD2121

### ISSUE THREAD

**Issue by yunzimo** [xyazzrany/Actions-Boot-Patch#1]
我在[unofficialtwrp](https://unofficialtwrp.com/twrp-3-7-0-root-vivo-s10-5g-pd2121/)找到了您的github，请问您是否曾经为vivo s10做过twrp的适配呢，我自己在编译中出现了不少问题，如果可以的话可以求一份您的twrp吗。

**Comment by xyazzrany** [comment]
以前做过已经删库了抱歉帮不到你
